---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supabase
  namespace: supabase-gitops
spec:
  interval: 30m
  chart:
    spec:
      chart: supabase
      version: 5.3.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    postgresql:
      auth:
        existingSecret: supabase-password
        