apiVersion: v1
kind: Secret
metadata:
    name: supabase-password
    namespace: supabase-gitops
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:rldPJ2xiA1c=,iv:CZm9KWVOEFwnkclwIdsIBRAW2GnSanRunisGLTeXZW8=,tag:hLBSFsyB9VD9o9x/H9xaog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-29T13:08:29Z"
    mac: ENC[AES256_GCM,data:UDVZktTl/0vNeAB/WzNOitTgQxzNxlq7E3TB/JzcGl1MRHZGo2qdD2El+JSJh7TIO8qv2EXC0/ZE01vRkD/ilbuPmNzsOoAkOBjrSDazmIvKuwUq4UtTXrvu4/M1hdLkDxuqeQiWTZqbbPCFrlP7iCIN1/Co4Z98GAqd6rtMsPM=,iv:r1TW72h/ogVAZols8foXOxbZ7wVuKDr4CIo2YoR1ACU=,tag:xkXuQMF2kA1ic4PZp6wLlg==,type:str]
    pgp:
        - created_at: "2024-08-29T13:08:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA97H9819A3nvARAA6t07CUfMmWVvkzE+GxWz4DLiNm6ffcfzYc+ijpCaVeFb
            EyzOcyBlWZWeKfGyix28lWkSEeFV9+J2+CVBcDhj5DcZ+DiKQpeDItvXDBz/vc3b
            CXs5eaaHKQhGf6EJCtP9LyX9kDn8t8PkHnNEv8D2FI5398CYSlqDdY6MSRdFq1fC
            Il1J03cuo0c1HZheMuj71PiuyrlMlltY7Vb5bfXLWhfFqfv0ZTQCv9yhc71j4APB
            q3SjcEIL/UeovQLRsL/JlvhCBRHdGL0F+HajbRGdrQtr3alhejw//2ZQ6GlwrJ0/
            +fO62EGbVsAu6WM0PI5o1DrQ/aiIzCM9+HwB6TkI538oK+M+N+i9rQZOCzeOy3AF
            nUaABxDvHEqxiG5Iim/9JmpiSvDT0xemZpkngQaac9n3NY7wyncL/yHjlP9OVlx7
            REZikZuKaxwhhAdKlovmT6Nh/1qL2SA7CgwJDmxZCpozLRZKBKZxH4bdGw/VzS5J
            vAeONxVmClqtJEi0XfoPZCgzoj6at3klLZ/O4qJu7Lvv5YiQy+RUNKRaT2HuiY3X
            DWHahB1YRxOB0wfCG9wmQgRSuo7p5gWvBE84RQIeDBO6G/AcZq6C2+ajPGeKCVgI
            a5JucOxcXNu4vr0QSf0kDfJORTmxpi/+IbHoP3K3l7/7pINOQ/CvGxrMSTYaS57S
            XgH3426yXTN4bZOluxqaVXnBLRul43eX26Q7k0MmKcjDibjIpK+93f626QP19CTJ
            ZbUX2JpqjEDuj8YElWD1mGSX1uFbQV0IW4w22+9CiH992JRx+FhbGaMWXTRXGYk=
            =8Trw
            -----END PGP MESSAGE-----
          fp: C6DFC9C21E0A29B5C98DB2ECBEE8200417922B2C
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
