---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-plugins-pvc
  namespace: metabase
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-db-pvc
  namespace: metabase
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
