---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metabase
  namespace: metabase
spec:
  interval: 75m
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: metabase
      version: 2.16.6
      sourceRef:
        kind: HelmRepository
        name: pmint93
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
    extraVolumeMounts:
      - name: metabase-plugins-pvc
        mountPath: /plugins
      - name: metabase-db-pvc
        mountPath: /metabase.db
    extraVolumes:
      - name: metabase-plugins-pvc
        persistentVolumeClaim:
          claimName: metabase-plugins-pvc
      - name: metabase-db-pvc
        persistentVolumeClaim:
          claimName: metabase-db-pvc