---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: loki
      version: 5.42.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    loki:
      commonConfig:
        replication_factor: 3
    singleBinary:
      replicas: 3
      persistence:
        enabled: false
    write:
      persistence:
        enabled: false
    read:
      persistence:
        enabled: false
    backend:
      persistence:
        enabled: false
    tableManager:
      retention_period: 52h
      persistence:
        enabled: false
