---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: percona
  namespace: percona
spec:
  interval: 75m
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: percona
      version: 1.13.7
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: flux-system
