# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# repos:
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v3.2.0
#     hooks:
#     -   id: trailing-whitespace
#     -   id: end-of-file-fixer
#     -   id: check-yaml
#     -   id: check-added-large-files
# -   repo: https://github.com/yuvipanda/pre-commit-hook-ensure-sops
#     rev: v1.0
#     hooks:
#     -   id: sops-encryption
#         # Uncomment to exclude all markdown files from encryption
#         #   exclude: *.\.md
#         files: .*sops.*




repos:
-   repo: hooks/pre-commit-hook-ensure-sops
    rev: v1.0
    hooks:
    -   id: sops-encryption
        # language: python
        # entry: python3 -m pre_commit_hook_ensure_sops
        # name: Ensure secrets are encrypted with sops
        exclude: ^\.sops\.yaml
        files: .*sops.*
