apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kube-prometheus-stack
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '55.0.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
  values:
    grafana:
      persistence:
        type: pvc
        enabled: true
        storageClassName: "longhorn"
        accessModes: ["ReadWriteOnce"]
        size: 500Mi

    alertmanager:
      alertmanagerSpec:
        retention: 60h
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: "longhorn"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
    prometheus:
      prometheusSpec:
        retention: 2d
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
           volumeClaimTemplate:
            spec:
              storageClassName: "longhorn"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 3Gi
    thanosRuler:
      thanosRulerSpec:
        retention: 24h
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: "longhorn"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
