apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: kube-prometheus-stack
spec:
  loadBalancerClass: tailscale
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: kube-prometheus-stack 
    app.kubernetes.io/name: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000