apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: netbox
    name: in-cluster
  project: default
  source:
    path: projects/netbox
    repoURL: https://github.com/mujak27/kustomize-helm-gitops-learn
    targetRevision: HEAD
