apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-operator
  namespace: infisical
spec:
  interval: 1h
  chart:
    spec:
      chart: secrets-operator
      version: 0.7.1
      sourceRef:
        kind: HelmRepository
        name: infisical
        namespace: flux-system
  # values: