apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: infisical-auth-token
  namespace: infisical
  annotations:
    kubernetes.io/service-account.name: "infisical-auth"
