apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-actions-runner-controller
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/flux/cluster/apps/infra/actions-runner-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-actions-runner-controller-runner
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/flux/cluster/apps/infra/actions-runner-controller/runner
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system