apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - https://github.com/K-Phoen/dark/config/crd
  # - https://github.com/K-Phoen/dark/config/rbac
  # - https://github.com/K-Phoen/dark/config/operator
  - crd.yaml