---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-cnpg-app
  namespace: flux-system
spec:
  interval: 1h
  path: ./muwujak-evergarden/k8s/flux/cluster/apps/db/cnpg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-cnpg-cluster
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: cluster-cnpg-app
  path: ./muwujak-evergarden/k8s/flux/cluster/apps/db/cnpg/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system