---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tile38
  namespace: tile38
spec:
  interval: 75m
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: custom-tile38
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: muwujak-evergarden-charts
        namespace: flux-system
