apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-16-cluster
  namespace: cnpg
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1-12
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
    storageClass: longhorn
  enableSuperuserAccess: true
  postgresql:
    pg_hba:
      - host all all 0.0.0.0/0 md5
      - host all all ::/0 md5
    parameters:
      max_connections: "600"
      max_slot_wal_keep_size: 10GB
      shared_buffers: 512MB
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
  monitoring:
    enablePodMonitor: true
  superuserSecret:
    name: cloudnative-pg-secret
