apiVersion: v1
kind: Secret
metadata:
  name: backup-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${SECRET_LONGHORN_BACKUP_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${SECRET_LONGHORN_BACKUP_ACCESS_KEY}
  AWS_ENDPOINTS: ${SECRET_LONGHORN_BACKUP_ENDPOINT}
