---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./longhorn-nfs-installation.yaml
  - release.yaml
  # - ./snapshot.yaml
  - tailscale-ingress.yaml
