apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret-vars
    namespace: flux-system
type: Opaque
stringData:
    SECRET_CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:FbCdpdOa9Q+lG8Ru2JLOYFfymI1E3yH54xgVBow2zJGnZceUSCdIzw==,iv:0ekjuE8AL89TDm2yyfgwRcdgwe8Dbh4WRSw1+Eaj06Y=,tag:SKg0/WCDMdY0ITmRjAvL+A==,type:str]
    SECRET_CLOUDFLARE_API_EMAIL: ENC[AES256_GCM,data:nJEz5KwSn+FY6ogpFevM2XnTkek2Mg0=,iv:/TU0xTl4QMJumJIY1VmSDf7wMHRJ1/Wcs88XUl1Z+z8=,tag:Lhu3f8uh4eAUJ3GwyJsRww==,type:str]
    SECRET_LOCAL_DOMAIN: ENC[AES256_GCM,data:pZbvI6NLw4w=,iv:fwwSQFvazC+zAdx+7udDXPvFEs3eGyg2cRzXe3mgDso=,tag:YPLC+pqSTFJ9Nz+/mGCzWw==,type:str]
    SECRET_TAILSCALE_CLIENT_ID: ENC[AES256_GCM,data:3vC5dXLZaSBvt1Asvm6krNc=,iv:8OrQcf+zLRNZRZZyy0l441BBPdKctrNQF9MfNzSEUbs=,tag:hkCwgKsbz3B9vFZHyU6ZPQ==,type:str]
    SECRET_TAILSCALE_CLIENT_SECRET: ENC[AES256_GCM,data:vkFsWwatFhJrjbwqzMny1Qa2voY99Uv6yWVORum4OHpYVIx1CU2lbAwsbsEhOrKlY+KTVkzTWCVyiftTO56k,iv:N8RYROouf9N8L3NFPtVlkyuq4zdUqyVM8NZC1JrXxx4=,tag:rBFdaPPX1DA6JF6oRcyRpA==,type:str]
    SECRET_INFISICAL_AUTH_SECRET: ENC[AES256_GCM,data:pYGSrtARL3JkHwAreMRQsSkFYXHYi41CwhTr2Px+q5GrSZQw2PAD6NV9rjY=,iv:JBiLVJl2hAnBplpXA0Y6W1oYcKlgtpTQayABbi/t/sY=,tag:it1qQxVJhnZnIsGbKFP+rQ==,type:str]
    SECRET_INFISICAL_ENCRYPTION_KEY: ENC[AES256_GCM,data:Rq9KwZN5+1mwLvkkl/2vLIYfuR6Is0TPx1HXwNUQ2fk=,iv:3RgwDnTiMAkyMbpqzBfWuiZiT5BxDQ1fUXssUUbdS+Q=,tag:cSXmS0JBC2F4mQVxc7trAA==,type:str]
    SECRET_LONGHORN_BACKUP_KEY_ID: ENC[AES256_GCM,data:764nMHmI1iN6ARh9gKqBOwUl3ww=,iv:PYpMyzcf+wFvj/5b6zVpZUVgWb3JYY/cCqIUQtLmAbk=,tag:Uu1xtNVegZ65gb3y6epHtQ==,type:str]
    SECRET_LONGHORN_BACKUP_ACCESS_KEY: ENC[AES256_GCM,data:7zR+aBj/v7/lQPenTkQGrRBMnuP8YHujGM2Paa5KUn/vbjyL3LPYmA==,iv:Jh5pdtCukC0XmX8XRBLq07+DYv4hdwdl5oCXJL8g/N4=,tag:IZK2SPr1keFhD5KHh7yvJg==,type:str]
    SECRET_LONGHORN_BACKUP_ENDPOINT: ENC[AES256_GCM,data:77FCKwF32v1DEKc6vDelyPiYOeZZzZYb,iv:FYlNPzMt2QchIKU4u2lL6xO+lVtYFh1qA+iYb0OfVNk=,tag:754igi1O9/5BnCza9kaiAw==,type:str]
    SECRET_NFS_SUBDIR_EXTERNAL_PROVISION_PATH: ENC[AES256_GCM,data:aTC8LpxlTFjF5N2mR1eVhaMMDfy+ciy266zHUstIlMNKbg==,iv:u/oY3YCraEg2chE2cqe8LwvtrsOCGJ/YJ/aUktecVyQ=,tag:uBU4O/pZdsfjsy2zP87Kmw==,type:str]
    SECRET_ZITADEL_MASTERKEY: ENC[AES256_GCM,data:9l+nfSkiNeMEEqZQcah3djk5FYxZ05yYeVafXcKzWpPTflgkNEx7FvCRqq8c2stNA4ZMc1MwESU/M+C4Ruue3Q==,iv:SZ/I3ZTA6vSHK2hVDa/3d1RiSjBlvoaY81emKGnafUg=,tag:M7G3qdqETXQYN4zcUzy6Nw==,type:str]
    SECRET_ZITADEL_CRDB_USER_PASSWORD: ENC[AES256_GCM,data:yTdPi9v82g==,iv:9kRb7XQVpEpQ6ILOJ0hRASw2d/qMk/BWcrv6XXWRdIo=,tag:lnSJKCxL57jcLeHbo11C+Q==,type:str]
    SECRET_ZITADEL_POSTGRES_PASSWORD: ENC[AES256_GCM,data:3c8kDP2t22s=,iv:q49lK/HiPut2KwjpDPPiWc/1uQhpNSLVegbqwfFMLn4=,tag:Wf+qL9JO/OBGTwz6yZggdg==,type:str]
    SECRET_POSTGRES_DB: ENC[AES256_GCM,data:TohfLWoimh8=,iv:SQr+/DFYCricIOkGDM48H4VS/Ngu89AwOYGKUpM2tSM=,tag:fhMIfPMU6iuOCc1dnJGVjg==,type:str]
    SECRET_POSTGRES_USER: ENC[AES256_GCM,data:U0Rywjod7Uc=,iv:oO7BRoKuXjiGmUIsXkawzXNp0fN8nZmpGsSFQx/hdDg=,tag:9FFs29g/Hf0INnS3CttI9g==,type:str]
    SECRET_POSTGRES_PASSWORD: ENC[AES256_GCM,data:8NWsyh3CaHM=,iv:4TNw4n1twhf8xBkrdh+7YzNES9QU0IM6fw9hjmBn2k4=,tag:nGFv3WaGwABCnlRPr2CSPg==,type:str]
    SECRET_CNPG_USERNAME: ENC[AES256_GCM,data:y9GFLaRXVWI=,iv:uwqUxPT+WiDPqhkioUDj44/2sVs9KPI1EiRf7FiMeC0=,tag:x++MkGRHf5IuuK3lZHQkeQ==,type:str]
    SECRET_CNPG_PASSWORD: ENC[AES256_GCM,data:m8FmQbhMm1o=,iv:Hx7tXLfNNlHQQ48qUISKSYlKXubZtrBmfNAZkRY0ro0=,tag:a9W3X0vsZnhvCsIwK9a1FA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-27T11:53:56Z"
    mac: ENC[AES256_GCM,data:MNm8gfPVf8/U4OIeLthtXwUw+BZZcEOnHMtrdgPqUdb6D6qQCzMUPytUnzW26k6EhHuD/pE+u/Vy3dqENnLUvBzFzCWdLyISdjq6JDllbDZNLabReurSQyW9mrHIbs9aFrq0SeKZ1T/+ytKOZvPNftr428eRYpBOcWCnu0iJ8BE=,iv:ZCvfY9IvXsMzHY4KrhBsOWuxVrQngpXQPgLOAUdhB8A=,tag:dXG95UkBdMOlCUcesaV7+Q==,type:str]
    pgp:
        - created_at: "2024-08-27T11:53:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA97H9819A3nvAQ/+LzfMBtjQwwqPi9GopmHryFDk6Jdma+L5bPgvaohaYDSK
            hsszuajHrRSciMU4P+0KJHv17R509iNSetcV8J8mZlPOAqs1cIL9nMZQLQlmshbz
            Pt3wX6pX+HrCNc1CQMKjxVpjBtSvskIQAHqw/vhdMMG47VpGKyEmxRdmUZEu6kBi
            3ORFevzQpG7xZWgjros8w3dYlZcp5/WW2O8sYnFjc05jtx994IwKwKB9VBl/hnQV
            Hr8vNIn/mIp6UagNbPf8h2AFMFRE92C1Z8FL5Ep0muYndIOQHiIiTFT8isp5cFxR
            Zq6kTX3zXY50oALlzeLRULOAflDQW2FvBhAhMbQZ3P9HFxAFODzWv0rlQU5AfWia
            UUoiHipQxFnv/dZDjZ5041egS19BEiLvoCICpHaIefjZ0KS6LOVwkdDvDT5whq48
            0OqPrLLIwG3OuEvyCEIBp//1fcuH9VWOg1uW2nrQu3rUgNBBsoIPRw6VMLR0IlPK
            uqN0tBsD8xPBr3BedfxI3bzhNUQm58eckT8nugcxg7zEA7ktkZISRKCaF9f2qgvo
            b3AG1MWk1bc+eg/6q9O3dGE5ZMJ8yAuPHyp8G8eAabfdtP4G97p1yTOyqU+JRY6F
            HTpSM08lLe/GDXbz5MAPZOlVphFZrVRZzK2rW8bZQ0zvBTMgAzwoK+rC60vj9W3S
            XgE13jNEUPnDsQDcCFZ8DDGylpaKBSKu6zkwPYXd1Yt/p/yHS5LOETv7GvBMxSZk
            /RBJ5Pk/d7qXHkG5R8pqWGW3AHe1Pkro+MaTCcj+NT8N6RbpNBOodqNI0IcNtuA=
            =zSjx
            -----END PGP MESSAGE-----
          fp: C6DFC9C21E0A29B5C98DB2ECBEE8200417922B2C
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
