apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret-vars
    namespace: flux-system
type: Opaque
stringData:
    SECRET_CLOUDFLARE_API_TOKEN: XK-Q4oBwew6_iUE5KYu-5p4J4NXnWepl8K3GXK5e
    SECRET_CLOUDFLARE_API_EMAIL: mujakoverflow@gmail.com
    SECRET_LOCAL_DOMAIN: mujak.id
    SECRET_TAILSCALE_CLIENT_ID: k9pLGYJjhN11CNTRL
    SECRET_TAILSCALE_CLIENT_SECRET: tskey-client-k9pLGYJjhN11CNTRL-svhkFGfWUYAd1DUkBi8MYAcB3pYVN3j2
    SECRET_INFISICAL_AUTH_SECRET: S6qO8K1nWot3ETZ2LnjC7TrBkR0BUazbFiAoAsa5EdI=
    SECRET_INFISICAL_ENCRYPTION_KEY: 4e1e27b5d22647e3aecd3af79d48c03e
    SECRET_LONGHORN_BACKUP_KEY_ID: wGalqxvTAtqixKNdTuTp
    SECRET_LONGHORN_BACKUP_ACCESS_KEY: dqDwx2JUJV3KpavBrvw5YwwBOLXq5s4f3voAVzYo
    SECRET_LONGHORN_BACKUP_ENDPOINT: http://10.227.1.201:9000
    SECRET_NFS_SUBDIR_EXTERNAL_PROVISION_PATH: /mnt/hakari-pool-1/kubernetes-nfs/
    SECRET_ZITADEL_MASTERKEY: 4VqvUx0s3U75gCoCgtoq7IhjY4NSg5DFLP1UzrjJvC85NdO8U9kDTqPqFKtVY76D
    SECRET_ZITADEL_CRDB_USER_PASSWORD: dummy
    SECRET_ZITADEL_POSTGRES_PASSWORD: dummy
    SECRET_POSTGRES_DB: postgres
    SECRET_POSTGRES_USER: postgres
    SECRET_POSTGRES_PASSWORD: postgres