apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret-vars
    namespace: flux-system
type: Opaque
stringData:
    SECRET_CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:8wVGp4uGrGHpG2j41e1iSV7acgKAoMXqP01k/ahOwHGSFqpi2QiSYg==,iv:PMC50frBBuER+VOqbMcj/1Sq6aSq9PITFGi635zc+Zk=,tag:OVTgzyeYJQSbdSsinC4Kyw==,type:str]
    SECRET_CLOUDFLARE_API_EMAIL: ENC[AES256_GCM,data:JGg2mAmjByRHrPeLIa3CbhiLK4rph7w=,iv:xPjrktm/XhMHZfWdcdexOo8FRxmXjgtgb4cY9QXW1UY=,tag:Zx/s/eyJD7RExGrNMq3Vlw==,type:str]
    SECRET_LOCAL_DOMAIN: ENC[AES256_GCM,data:SNkFZfzMVwE=,iv:usi6wNe0ZWfBVovvd/AUnLdzhq2SAPjPwDVrQZjSAwc=,tag:XfB4xfJLT0AbPaPWB9rndQ==,type:str]
    SECRET_TAILSCALE_CLIENT_ID: ENC[AES256_GCM,data:jofZKS67PoBVo8qPZ59Jhsc=,iv:vKNZPQqiLr/72hNnVxvaDK4xUil/bv/Ul1jMZbIW83M=,tag:x6e7s3NgNiMoSHOgOs0EEQ==,type:str]
    SECRET_TAILSCALE_CLIENT_SECRET: ENC[AES256_GCM,data:/8j/ejFtp2Jbpqroy0q9Rx+Yq7wwHlm/rbiiEl/wwQSaQtZhlBFaZi3GJ03UxJ7/c+5LhUatpvp21v+h85kH,iv:Tz8Q/HfTEN55kn76vxhsXfFRs5chPUWG7nvUTZpJaTA=,tag:Vg6p/04fYa2UHWrEB+7E+Q==,type:str]
    SECRET_INFISICAL_AUTH_SECRET: ENC[AES256_GCM,data:S1LrAOFlZ5e2I1uFvKpSgUMomKEWobV3WmBrR3E1ga3/KTX8FDN1V3zWHs4=,iv:oiJjVjhNq+n+Yl2wlK4sI0Sfy1P7ovXr317wcFFgAMo=,tag:qa6WfiF585/F8FHSmEHcyw==,type:str]
    SECRET_INFISICAL_ENCRYPTION_KEY: ENC[AES256_GCM,data:vNFFzZIQIefHLOv5Evb667mnQs/eMKu6FHeJqVMM98o=,iv:HVThuUhySTx2rAigiAOsaPrIgdQpD9/1kDtHT3VRP/g=,tag:QNv5ZWEPnNN+rVqufgSRVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-27T15:20:28Z"
    mac: ENC[AES256_GCM,data:od7rSWPrSkreLOTjeltpcLADCOp5+tMS8rJ8iewugD/gK1372oA3oV/GuucnPLa9FEYpA8+bYgPcA0HopoeTyKcDOj8V6s7SI7pVUbEkrghulhYKxuFu3suxviIPLdWcf7YdIrGsovKAeevQSnr2qjs9HzYgFdngDgGd3le3830=,iv:3YjRpPjetauJOIByqNw5xQfRkJ/p4QzFESzBhV5N8sc=,tag:BKUwbKs7dK1JI6Jba306Lw==,type:str]
    pgp:
        - created_at: "2024-07-27T15:20:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA97H9819A3nvAQ/8CGKZCjbglGTsorMUnbaPEtCv4/pI0pr86T5SJz/RWl9p
            4mDsudhabzaQLB/GP8sb5HiabjEXXTteZ07qa9KI1u2bmULd7jScxynaikF54VSd
            l0D8FJSGbpjG6+5OuhB7S6jgyDwPNOTqzDuLUFh3fW98hWLwCWnFpNsyjAWXVD5a
            NvvYza1pdPnSGGBG7ni7rmsle2jU8TvckA+yK2a2Zho6IvXt7V13vXmjeZbgf+if
            ttcMu9IbLb5VRzDo1gVHaCv3PkUxHZHpGuJGhoOc67oHgOAlIFFUMnI1URRwBBEV
            5hHKGV6JJGPXgt162Mwbpg3UwhPFqJu7Gg0eFaNvQTM9GTp8wUPJJUbBLK5+Mv5O
            g00AAd13gpNUp8uYhUImwHiBn+wfM4N1gzbL5XH3sB4LV1iVmj4n4f4RWBB3W6OB
            2dKsr6J+6sTxW20AX6RDyFP0MMcYUgaI3JwfzNvS5WJl0UCL/jB6Foi9e5w1aP5C
            eA+sp49YhkaU0ovyzXDtBIr9qDCMEAIszEvYd4rFmyGkM20IcHUZ9p5nefGown4j
            DbpRkN021TXw8WZ+QZyPn+8gCxffupeIkbK1NIr9r7D1wdJr4z2AgBWNyH69jZS6
            MaB/fBtA25uggCqNTkyhuQqmVciPvM0FB31XQGzTR+x30/0RD4FQxXa0wLB0UE3S
            XgHT+N4GIVCytDOXpSjYU9ywZrUUeNBlZupyb5xxllVJg8EVaD2gWl/CZpDoHKRc
            1lo4YdjeSsnWciVhZK7C2Rp1c3erO9SVqLCaYXRlyn5N6ROrNI0o1bOPoWVBxVM=
            =AXqi
            -----END PGP MESSAGE-----
          fp: C6DFC9C21E0A29B5C98DB2ECBEE8200417922B2C
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
