apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-secret
data:
    POSTGRES_DB: '${SECRET_POSTGRES_DB}'
    POSTGRES_USER: '${SECRET_POSTGRES_USER}'
    POSTGRES_PASSWORD: '${SECRET_POSTGRES_PASSWORD}'