apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - pvc.yaml
  - pvc-helm.yaml
  - release.yaml
  - service.yaml

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: namespaceTransformer
      namespace: postgres
    unsetOnly: false
