---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: promtail
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: 6.15.5
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  values:
    config:
      lokiAddress: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
      clients:
        - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
      snippets:
        # common:
        # - action: replace
        #   source_labels:
        #     - __meta_kubernetes_namespace
        #   target_label: namespace
        # pipeline_stages:
        pipelineStages:
        - cri: {}
        - 
          match:
            selector: '{__meta_kubernetes_namespace="kube-system"}'
            action: drop
            drop_counter_reason: drop1
        - 
          match:
            selector: '{namespace="kube-system"}'
            action: drop
            drop_counter_reason: drop2
        # - drop:
        #     source:     "namespace"
        #     expression: "(loki|promtail|kube-system)"
        # - drop:
        #     source:     "__meta_kubernetes_namespace"
        #     expression: "(loki|promtail|kube-system)"
        # scrape_configs:
        # - job_name: filter-namespace
        #   # static_configs:
        #   # <CONFIG...>

# namespace to exclude
# default
# longhorn-system
# promtail
# kube-system