apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-mageai
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/flux/cluster/apps/default/mageai/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system