---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: var-kustomization
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/flux/cluster/var
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-configmap-vars
      - kind: Secret
        name: cluster-secret-vars
  decryption:
    provider: sops
    secretRef:
      name: sops-pgp
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-pgp
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: cluster-configmap-vars
              - kind: Secret
                name: cluster-secret-vars
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization