---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-percona-nfs-pxc-db
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/flux/cluster/apps/db/percona-nfs/pxc-db
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-percona-nfs-pxc-operator
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/flux/cluster/apps/db/percona-nfs/pxc-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system