---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: infisical
  namespace: flux-system
spec:
  interval: 10m
  url: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/

  timeout: 3m