apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - secret.yaml
  - svc.yaml
  - tailscale-ingress.yaml

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: namespaceTransformer
      namespace: infisical
    unsetOnly: true
