---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: infisical
  namespace: infisical
spec:
  interval: 75m
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: infisical-standalone
      version: 1.0.8
      sourceRef:
        kind: HelmRepository
        name: infisical
        namespace: flux-system
  values:
    infisical:
      image:
        repository: infisical/infisical
        tag: "v0.46.2-postgres" #<-- update
        pullPolicy: IfNotPresent
