apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
  namespace: infisical
type: Opaque
stringData:
  AUTH_SECRET: ${SECRET_INFISICAL_ENCRYPTION_KEY}
  ENCRYPTION_KEY: ${SECRET_INFISICAL_AUTH_KEY}
  # REDIS_URL: <>
  # DB_CONNECTION_URI: <>