apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-percona
  namespace: flux-system
spec:
  interval: 1h
  path: ./flux/cluster/apps/db/percona/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system