---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - 
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
            hugepages-2Mi: "512Mi"
            hugepages-1Gi: "1Gi"
          requests:
            cpu: "100m"
            memory: "512Mi"
            hugepages-2Mi: "512Mi"
            hugepages-1Gi: "1Gi"
        image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: test12345
        - name: MYSQL_DATABASE
          value: terrex
        - name: MYSQL_USER
          value: muwujak
        - name: MYSQL_PASSWORD
          value: test12345
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
        - name: mysql-config-pvc
          mountPath: /etc/mysql/conf.d/
        - mountPath: /hugepages-2Mi
          name: hugepage-2mi
        - mountPath: /hugepages-1Gi
          name: hugepage-1gi
      volumes:
      - name: mysql-pvc
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-config-pvc
        persistentVolumeClaim:
          claimName: mysql-config-pvc
      - name: hugepage-2mi
        emptyDir:
          medium: HugePages-2Mi
      - name: hugepage-1gi
        emptyDir:
          medium: HugePages-1Gi
