apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - pvc-config.yaml
  - tailscale-ingress.yaml

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: namespaceTransformer
      namespace: mysql
    unsetOnly: true
