---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-config-pvc
  namespace: mysql
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
