apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mage-volume
  namespace: mageai
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-provision
  resources:
    requests:
      storage: 2Gi