---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mageai
  namespace: mageai
spec:
  interval: 1m
  chart:
    spec:
      chart: mageai
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: mageai
        namespace: flux-system
  values:
    image:
      repository: mageai/mageai
      pullPolicy: "Always"
      tag: "0.9.73"
    replicaCount: 1
    standaloneScheduler: false
    scheduler:
      replicaCount: 2
      name: mageai-scheduler
    webServer:
      replicaCount: 1
      name: mageai-webserver
    redis:
      enabled: true
      architecture: standalone
    service:
      type: NodePort
      port: 6789
    # extraVolumeMounts:
    #   - name: mage-fs
    #     mountPath: /home/src
    # extraVolumes:
    #   - name: mage-fs
    #     persistentVolumeClaim:
    #       claimName: mage-volume
    existingSecret: mageai-secret


    extraEnvs:
      - name: KUBE_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace