apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - pull-secret.yaml
  - release.yaml

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: namespaceTransformer
      namespace: actions-runner-controller
    unsetOnly: true
