apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: actions-runner-scale-set
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    runnerScaleSetName: homelab-action-runner
    githubConfigUrl: https://github.com/muwujak
    githubConfigSecret: actions-runner-controller-github-app-credentials
    minRunners: 2
    maxRunners: 5
    containerMode:
      type: dind
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/onedr0p/actions-runner:2.319.1
            command: ["/home/runner/run.sh"]
    controllerServiceAccount:
      name: actions-runner-controller
      namespace: actions-runner-controller