apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/flux/cluster/apps/storage/nfs-subdir-external-provisioner/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system