apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: debian
    command:
      - tail
      - -f 
      - /dev/null
    imagePullPolicy: IfNotPresent
    name: debian
  restartPolicy: Always