apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: weibeld/ubuntu-networking
        command:
          - tail
          - -f 
          - /dev/null
        imagePullPolicy: IfNotPresent
        name: debian
        volumeMounts:
        - name: config
          mountPath: /mnt/config  # Adjust mountPath as necessary
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: busybox-nfs-volume
