apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-nfs-volume
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-provision
  resources:
    requests:
      storage: 1Gi