---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: percona-pxc-db
  namespace: percona-helm-2
spec:
  interval: 75m
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: pxc-db
      version: 1.14.3
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: flux-system
  values:
    pxc:
      size: 2
      resources:
        requests:
          memory: 100M
          cpu: 100m
      persistence:
        enabled: true
        storageClass: "longhorn"
        size: 10Gi

      # If you set this to true the cluster will be created without TLS
      disableTLS: false


    haproxy:
      enabled: true
      size: 2
      resources:
        requests:
          memory: 100M
          cpu: 600m

    proxysql:
      enabled: false

    logcollector:
      resources:
        requests:
          memory: 100M
          cpu: 100m
        limits: {}


    backup:
      enabled: false

    # backup:
    #   enabled: false
    #   # allowParallel: true
    #   image:
    #     repository: percona/percona-xtradb-cluster-operator
    #     tag: 1.13.0-pxc8.0-backup-pxb8.0.32
    #   # backoffLimit: 6
    #   # serviceAccountName: percona-xtradb-cluster-operator
    #   # imagePullPolicy: Always
    #   imagePullSecrets: []
    #   # - name: private-registry-credentials
    #   pitr:
    #     enabled: false
    #     storageName: s3-us-west-binlogs
    #     timeBetweenUploads: 60
    #     resources:
    #       requests: {}
    #       limits: {}
    #   storages: {}
    #     # fs-pvc:
    #     #   type: filesystem
    #     #   volume:
    #     #     persistentVolumeClaim:
    #     #       storageClassName: standard
    #     #       accessModes: ["ReadWriteOnce"]
    #     #       resources:
    #     #         requests:
    #     #           storage: 6Gi
    #     # s3-us-west:
    #     #   type: s3
    #     #   verifyTLS: true
    #     #   nodeSelector:
    #     #     storage: tape
    #     #     backupWorker: 'True'
    #     #   resources:
    #     #     requests:
    #     #       memory: 1G
    #     #       cpu: 600m
    #     #   affinity:
    #     #     nodeAffinity:
    #     #       requiredDuringSchedulingIgnoredDuringExecution:
    #     #         nodeSelectorTerms:
    #     #         - matchExpressions:
    #     #           - key: backupWorker
    #     #             operator: In
    #     #             values:
    #     #             - 'True'
    #     #   tolerations:
    #     #     - key: "backupWorker"
    #     #       operator: "Equal"
    #     #       value: "True"
    #     #       effect: "NoSchedule"
    #     #   annotations:
    #     #     testName: scheduled-backup
    #     #   labels:
    #     #     backupWorker: 'True'
    #     #   schedulerName: 'default-scheduler'
    #     #   priorityClassName: 'high-priority'
    #     #   containerSecurityContext:
    #     #     privileged: true
    #     #   podSecurityContext:
    #     #     fsGroup: 1001
    #     #     supplementalGroups: [1001, 1002, 1003]
    #     #   s3:
    #     #     bucket: S3-BACKUP-BUCKET-NAME-HERE
    #     #     # Use credentialsSecret OR credentialsAccessKey/credentialsSecretKey
    #     #     credentialsSecret: my-cluster-name-backup-s3
    #     #     #credentialsAccessKey: REPLACE-WITH-AWS-ACCESS-KEY
    #     #     #credentialsSecretKey: REPLACE-WITH-AWS-SECRET-KEY
    #     #     region: us-west-2
    #     #     endpointUrl: https://sfo2.digitaloceanspaces.com
    #     # s3-us-west-binlogs:
    #     #   type: s3
    #     #   s3:
    #     #     bucket: S3-BACKUP-BUCKET-NAME-HERE/DIRECTORY
    #     #     credentialsSecret: my-cluster-name-backup-s3
    #     #     region: us-west-2
    #     #     endpointUrl: https://sfo2.digitaloceanspaces.com
    #     # azure-blob:
    #     #   type: azure
    #     #   azure:
    #     #     credentialsSecret: azure-secret
    #     #     container: test
    #     #     endpointUrl: https://accountName.blob.core.windows.net
    #     #     storageClass: Hot

    #   schedule: []
    #     # - name: "daily-backup"
    #     #   schedule: "0 0 * * *"
    #     #   keep: 5
    #     #   storageName: fs-pvc
    #     # - name: "sat-night-backup"
    #     #   schedule: "0 0 * * 6"
    #     #   keep: 3
    #     #   storageName: s3-us-west