---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: percona-pxc-db
  namespace: percona-nfs-helm-1
spec:
  interval: 75m
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: pxc-db
      version: 1.14.3
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: flux-system
  values:
    pxc:
      size: 2
      resources:
        requests:
          memory: 100M
          cpu: 100m
      persistence:
        enabled: true
        storageClass: "nfs-provision"
        size: 10Gi

      # If you set this to true the cluster will be created without TLS
      disableTLS: false


    haproxy:
      enabled: true
      size: 2
      resources:
        requests:
          memory: 100M
          cpu: 600m

    proxysql:
      enabled: false

    logcollector:
      resources:
        requests:
          memory: 100M
          cpu: 100m
        limits: {}



    backup:
      enabled: false