apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-ingress-nginx
  namespace: flux-system
spec:
  interval: 1h
  path: ./k8s/flux/cluster/apps/network/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
