---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: percona-pxc-operator
  namespace: percona-helm-1
spec:
  interval: 75m
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: pxc-operator
      version: 1.14.2
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: flux-system
  values: